triggers:
  - interceptor: github
    secret: abc
    eventType: "push"
    filter: "body.action in ['opened', 'synchronize', 'reopened']" # https://github.com/TomFrost/Jexl
  - interceptor: github
    secret: bcd
    eventType: "push"
    filter: "body.action in ['synchronize']"
  - interceptor: manual_dispatch
  - interceptor: schedule
