triggers:
  - interceptor: github
    secret: {}
    eventType: "push"
    filter: "body.action in ['opened', 'synchronize', 'reopened']" # https://github.com/TomFrost/Jexl
  - interceptor: github
    secret: {}
    eventType: "push"
    filter: "body.action in ['synchronize']" # https://github.com/TomFrost/Jexl