name: Node.js Package

on:
  push:
    tags:
      - "release/**"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: engine publish
        run: npm publish
        if: ${{ contains(github.ref, 'engine')}}
        working-directory: ./packages/engine
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: curl https://npmmirror.com/sync/@serverless-devs/s
